version: 2
jobs:
  build:
    docker:
      - image: gcr.io/planet-4-151612/p4-builder:latest
    steps:
      - checkout
      - run: echo "A first hello"
      - run: mkdir -p my_workspace
      - run: echo "Trying out workspaces" > my_workspace/echo-output
