version: 2
jobs:
  build:
    docker:
      - image: gcr.io/planet-4-151612/p4-builder:latest
    working_directory: ~/
    steps:
      - setup_remote_docker
      - run: activate-gcloud-account.sh
      - run: mkdir -p /tmp/workspace/var
      - run: mkdir -p /tmp/workspace/src
      - run: echo "${CIRCLE_BUILD_NUM}" > /tmp/workspace/var/circle-build-num
      - run: git clone https://github.com/greenpeace/planet4-nro-generator.git
      - run: echo "${PRIVKEY}" > ~/planet4-nro-generator/id_rsa && chmod 600 ~/planet4-nro-generator/id_rsa
      - run: git config --global user.email "larry.titus@greenpeace.org"
      - run: git config --global user.name "Larry Titus"
      - run: sed -i '/-v/d' ~/planet4-nro-generator/Makefile
      - run: sed -i 's/VOLUME \/app\/secrets/COPY .\/id_rsa \/root\/.ssh\//g' ~/planet4-nro-generator/Dockerfile
      - run: >
          cd ~/planet4-nro-generator/ && printf "%s\n" \
          "$CIRCLE_TOKEN" \
          "$GITHUB_OAUTH_TOKEN" \
          "$MYSQL_PRODUCTION_ROOT_USER" \
          "$MYSQL_PRODUCTION_ROOT_PASSWORD" \
          "$MYSQL_DEVELOPMENT_ROOT_USER" \
          "$MYSQL_DEVELOPMENT_ROOT_PASSWORD" \
          "$NRO" \
          "$APP_HOSTPATH" \
          "$GITHUB_REPOSITORY_NAME" \
          "$CONTAINER_PREFIX" \
          "$GITHUB_USER_EMAIL" \
          "$GITHUB_USER_NAME" \
          "$MAKE_DEVELOP" \
          "$MAKE_RELEASE" \
          "$MAKE_MASTER" \
          "$NEWRELIC_APPNAME" \
          "$MYSQL_USERNAME" \
          "$MYSQL_PASSWORD" \
          "$STATELESS_BUCKET_LOCATION" \
          | ./configure.sh
