version: 2
jobs:
  build:
    docker:
      - image: gcr.io/planet-4-151612/p4-builder:latest
    working_directory: ~/
    steps:
      - setup_remote_docker
      - run: activate-gcloud-account.sh
      - run: mkdir -p /tmp/workspace/var
      - run: mkdir -p /tmp/workspace/src
      - run: echo "${CIRCLE_BUILD_NUM}" > /tmp/workspace/var/circle-build-num
